steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mongodb-cloudrun', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/mongodb-cloudrun']
images:
- 'gcr.io/$PROJECT_ID/mongodb-cloudrun'
options:
  logging: CLOUD_LOGGING_ONLY
